From Essential Math for Data Science Take Control of Your Data with Fundamental Linear Algebra, Probability, and Statistics, First... (Thomas Nield)

In [1]:
import numpy as np


$
A = \begin{pmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9
\end{pmatrix}
$

première colonne $\hat{i}=\begin{pmatrix}1\\4\\7\end{pmatrix}$

$
\begin{bmatrix} x_{\text{new}} \\ y_{\text{new}} \end{bmatrix} = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} ax + by \\ cx + dy \end{bmatrix}
$


In [11]:
basis = np.array(
[[3, 0],
[0, 2]]
)

In [12]:
v = np.array([2,1])

In [13]:
basis.dot(v)

array([6, 2])

$
\begin{bmatrix} a & b \\ c & d \end{bmatrix} \begin{bmatrix} e & f \\ g & h \end{bmatrix} = \begin{bmatrix} ae + bg & af + bh \\ ce + dg & cf + dh \end{bmatrix}
$


In [14]:
from numpy import array

In [15]:
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

In [16]:
transform1

array([[ 0, -1],
       [ 1,  0]])

In [17]:
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

you can combine the two matrices simply using the matmul() or @ operator

In [18]:
combined = transform2 @ transform1

In [19]:
combined

array([[ 1, -1],
       [ 1,  0]])